/****** Object:  View [dbo].[v_multidimensional]    Script Date: 13/09/2021 15:17:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO 
CREATE TABLE [dbo].[SUBINDICATOR_DATA](
	[INDICATOR_CODE] [varchar](50) NOT NULL,
	[SUBINDICATOR_CODE] [varchar](50) NOT NULL,
	[TIME_PERIOD] [int] NULL,
	[REF_AREA] [varchar](50) NULL,
	[SEX] [varchar](50) NULL,
	[AGE] [varchar](50) NULL,
	[URBANISATION] [varchar](50) NULL,
	[EDUCATION] [varchar](50) NULL,
	[ACTIVITY] [varchar](50) NULL,
	[BREAKDOWN] [varchar](50) NULL,
	[QUINTILE] [varchar](50) NULL,
	[OBS_VALUE] [float] NULL,
	[UNIT_MULT] [varchar](50) NULL,
	[UNIT_MEASURE] [varchar](50) NULL,
	[OBS_STATUS] [varchar](50) NULL,
	[Income] [varchar](50) NULL,
	[REPORTING_TYPE] [varchar](50) NULL,
	[TIME_DETAIL] [varchar](50) NULL,
	[COMMENT_OBS] [ntext] NULL,
	[BASE_PER] [varchar](50) NULL,
	[SOURCE_DETAIL] [ntext] NULL,
	[SOURCE_DETAIL_AR] [ntext] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Index [ClusteredIndex-20210922-180952]    Script Date: 18/11/2021 11:09:34 ******/
CREATE CLUSTERED INDEX [ClusteredIndex-indcode] ON [dbo].[SUBINDICATOR_DATA]
(
	[INDICATOR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [INDIC_SUBind]    Script Date: 18/11/2021 11:10:44 ******/
CREATE NONCLUSTERED INDEX [INDIC_SUBind] ON [dbo].[SUBINDICATOR_DATA]
(
	[INDICATOR_CODE] ASC,
	[SUBINDICATOR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Indx_ind]    Script Date: 18/11/2021 11:11:24 ******/
CREATE NONCLUSTERED INDEX [Indx_subind] ON [dbo].[SUBINDICATOR_DATA]
(
	[SUBINDICATOR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( INDICATOR_CODE ) references INDICATOR(indicator_Code)
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( SUBINDICATOR_CODE ) references SUBINDICATOR(SUBindicator_Code)

alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [ACTIVITY] ) references CL_ACTIVITY ([CODE])
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [AGE] ) references [CL_AGE] ([CODE])
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [BREAKDOWN] ) references [CL_BREAKDOWN] ([CODE])

alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( EDUCATION ) references [CL_EDUCATION] ([CODE])
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [QUINTILE] ) references [CL_QUINTILE] ([CODE])
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [REF_AREA] ) references [CL_REF_AREA] ([CODE])
alter table [SUBINDICATOR_DATA] add FOREIGN KEY ( [SEX] ) references [CL_SEX] ([CODE])

go

