USE [sdgs_palestina]
GO

/****** Object:  Index [PK_Users]    Script Date: 17/11/2019 16:59:30 ******/
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [PK_Users] PRIMARY KEY NONCLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UK_username]    Script Date: 17/11/2019 16:59:30 ******/
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [UK_username] UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIMENSION] ADD  DEFAULT ((0)) FOR [IS_TIME]
GO
ALTER TABLE [dbo].[DIMENSION] ADD  DEFAULT ((0)) FOR [INT_CODE]
GO
ALTER TABLE [dbo].[Subindicator] ADD  DEFAULT ((0)) FOR [Is_Uploaded]
GO
ALTER TABLE [dbo].[Subindicator] ADD  DEFAULT ((1)) FOR [Is_Valid]
GO
ALTER TABLE [dbo].[User_INDICATOR]  WITH CHECK ADD  CONSTRAINT [FK_User_INDICATOR_Ind] FOREIGN KEY([IND_CODE])
REFERENCES [dbo].[Indicator] ([Indicator_Code])
GO
ALTER TABLE [dbo].[User_INDICATOR] CHECK CONSTRAINT [FK_User_INDICATOR_Ind]
GO
ALTER TABLE [dbo].[User_INDICATOR]  WITH CHECK ADD  CONSTRAINT [FK_User_INDICATOR_User] FOREIGN KEY([User_ID])
REFERENCES [dbo].[Users] ([User_ID])
GO
ALTER TABLE [dbo].[User_INDICATOR] CHECK CONSTRAINT [FK_User_INDICATOR_User]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([Role_ID])
REFERENCES [dbo].[Roles] ([Role_ID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
