ALTER TABLE [Subindicator]
ADD 
    UNIT_MULT nvarchar(50),
    UNIT_MEASURE nvarchar(50),
	OBS_STATUS nvarchar(50);

UPDATE S
SET S.UNIT_MULT = SD.UNIT_MULT
FROM [Subindicator] S
INNER JOIN [SUBINDICATOR_DATA] SD
    ON S.[INDICATOR_CODE] = SD.[INDICATOR_CODE]
	AND S.[SUBINDICATOR_CODE] = SD.[SUBINDICATOR_CODE]
WHERE SD.UNIT_MULT is not null;

UPDATE S
SET S.UNIT_MEASURE = SD.UNIT_MEASURE
FROM [Subindicator] S
INNER JOIN [SUBINDICATOR_DATA] SD
    ON S.[INDICATOR_CODE] = SD.[INDICATOR_CODE]
	AND S.[SUBINDICATOR_CODE] = SD.[SUBINDICATOR_CODE]
WHERE SD.UNIT_MEASURE is not null;

UPDATE S
SET S.OBS_STATUS = SD.OBS_STATUS
FROM [Subindicator] S
INNER JOIN [SUBINDICATOR_DATA] SD
    ON S.[INDICATOR_CODE] = SD.[INDICATOR_CODE]
	AND S.[SUBINDICATOR_CODE] = SD.[SUBINDICATOR_CODE]
WHERE SD.OBS_STATUS is not null;

