USE [pxweb_sdgs];

INSERT INTO "DATASTORAGE" (PRODUCTCODE, SERVERNAME, DATABASENAME, USERID, LOGDATE) VALUES ('001', 'local', 'pxweb_sdgs', 'SDGS', GETDATE());
INSERT INTO "TIMESCALE" (TIMESCALE, PRESTEXT, REGULAR, TIMEUNIT, FREQUENCY, STOREFORMAT, USERID, LOGDATE, TIMESCALEPRES) VALUES ('year', 'year', 'Y', 'A', '1', 'yyyy', 'SDGS', GETDATE(), 'N');
INSERT INTO "ORGANIZATION" (ORGANIZATIONCODE, ORGANIZATIONNAME, USERID, LOGDATE, WEBADDRESS) VALUES ('PCBS', 'Palestinian Central Bureau of Statistics', 'SDGS', GETDATE(), 'http://www.pcbs.gov.ps')
INSERT INTO "METABASEINFO" (MODEL, MODELVERSION, DATABASEROLE) VALUES ('MACRO', '2.3', 'PROD');
INSERT INTO "TEXTCATALOG" (TEXTCATALOGNO, TEXTTYPE, PRESTEXT, DESCRIPTION, USERID, LOGDATE) VALUES ('1', 'ContentsVariable', 'OBS', 'None', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('MENULEVELS', '4', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('DATANOTAVAILABLE', '3', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('DATANOTESUM', '4', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('DATASYMBOLNIL', '1', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('DATASYMBOLSUM', '5', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('DEFAULTCODEMISSINGLINE', '1', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('KEYSUPPERLIMIT', '100000', 'SDGS', GETDATE());
INSERT INTO "METAADM" (PROPERTY, VALUE, USERID, LOGDATE) VALUES ('PXDATAFORMAT', 'MATRIX', 'SDGS', GETDATE());
Insert into "SPECIALCHARACTER" (CHARACTERTYPE,PRESCHARACTER,AGGREGPOSSIBLE,DATACELLPRES,DATACELLFILLED,PRESTEXT,USERID,LOGDATE) values ('3','..','N','N','0','..','SDGS',GETDATE());
Insert into "SPECIALCHARACTER" (CHARACTERTYPE,PRESCHARACTER,AGGREGPOSSIBLE,DATACELLPRES,DATACELLFILLED,PRESTEXT,USERID,LOGDATE) values ('4','*','Y','Y','0','*','SDGS',GETDATE());
Insert into "SPECIALCHARACTER" (CHARACTERTYPE,PRESCHARACTER,AGGREGPOSSIBLE,DATACELLPRES,DATACELLFILLED,PRESTEXT,USERID,LOGDATE) values ('5','*','N','N','0','*','SDGS',GETDATE());
Insert into "SPECIALCHARACTER" (CHARACTERTYPE,PRESCHARACTER,AGGREGPOSSIBLE,DATACELLPRES,DATACELLFILLED,PRESTEXT,USERID,LOGDATE) values ('2','-','Y','Y','0','-','SDGS',GETDATE());
Insert into "SPECIALCHARACTER" (CHARACTERTYPE,PRESCHARACTER,AGGREGPOSSIBLE,DATACELLPRES,DATACELLFILLED,PRESTEXT,USERID,LOGDATE) values ('1','-','Y','N','0','Zero','SDGS',GETDATE());

INSERT INTO "TIMESCALE_ENG" (TIMESCALE, PRESTEXT, USERID, LOGDATE) VALUES ('year', 'year', 'SDGS', GETDATE());
INSERT INTO "ORGANIZATION_ENG" (ORGANIZATIONCODE, ORGANIZATIONNAME, USERID, LOGDATE, WEBADDRESS) VALUES ('PCBS', 'Palestinian Central Bureau of Statistics', 'SDGS', GETDATE(), 'http://www.pcbs.gov.ps')
INSERT INTO "TEXTCATALOG_ENG" (TEXTCATALOGNO, TEXTTYPE, PRESTEXT, DESCRIPTION, USERID, LOGDATE) VALUES ('1', 'ContentsVariable', 'OBS', 'None', 'SDGS', GETDATE());
Insert into "SPECIALCHARACTER_ENG" (CHARACTERTYPE,PRESCHARACTER,PRESTEXT,USERID,LOGDATE) values ('3','..','..','SDGS',GETDATE());
Insert into "SPECIALCHARACTER_ENG" (CHARACTERTYPE,PRESCHARACTER,PRESTEXT,USERID,LOGDATE) values ('4','*','*','SDGS',GETDATE());
Insert into "SPECIALCHARACTER_ENG" (CHARACTERTYPE,PRESCHARACTER,PRESTEXT,USERID,LOGDATE) values ('5','*','*','SDGS',GETDATE());
Insert into "SPECIALCHARACTER_ENG" (CHARACTERTYPE,PRESCHARACTER,PRESTEXT,USERID,LOGDATE) values ('2','-','-','SDGS',GETDATE());
Insert into "SPECIALCHARACTER_ENG" (CHARACTERTYPE,PRESCHARACTER,PRESTEXT,USERID,LOGDATE) values ('1','-','Zero','SDGS',GETDATE());
